### PR TITLE
Add Lahr/Schwarzwald

### PR DESCRIPTION
**Pull request by ubergesundheit**

### CODE REVIEW

**Comment by konstin** [comment]
Thanks!

**Comment by ubergesundheit** [comment]
:sweat_smile: I didn't test this, hope the values are right

**Comment by eFrane** [comment]
I've been planning to add a validation check for PRs to the endpoint list for ages 🙈, hopefully I'll get to that soonish.

**Comment by ubergesundheit** [comment]
Ping @nalxnet

**Comment by nalxnet** [comment]
Thanks for pinging, the values are lookin good. Will test this when setting MST up on the production VM.

**Pull request merged**
