### PR TITLE
Updates to SD.net RIM instances hosted by KDVZ Frechen

### LINKED ISSUE #9: New endpoints for SD.NET RIM hosted by KZVD Frechen
https://gist.github.com/stv0g/4f960ab635c8438de76428b52232849c

### PR DESCRIPTION
**Pull request by stv0g**
Closes #9

### CODE REVIEW

**Comment by konstin** [comment]
Thank you!

I wonder though wh the new file is shorter than the old version; Were there some broken endpoints you removed?

**Comment by stv0g** [comment]
Hi @konstin,

> Were there some broken endpoints you removed?

No, instead I removed a few duplicated endpoints. The RIS hosted by KDVZ are usually available via two domains.
This led to some duplication.

**Comment by konstin** [comment]
Not sure how that happened, but there seem to be merge conflicts now

**Comment by stv0g** [comment]
I will give this another try and rebase it on master

**Review by eFrane — APPROVED** [review]
Thanks a lot!

**Comment by eFrane** [comment]
As much as this change is wonderful, I just spent about half an our failing at merging it. :(

**Comment by konstin** [comment]
i created a merge by first sorting and then manually stepping through the diff: https://gist.github.com/konstin/8f1abb88e3975075dfd224b1c3df716d . No idea though how to ever integrate this into the git history again :sweat_smile: 

If we use this merge i'd add the following as sort_endpoints.py (https://github.com/OParl/resources/compare/manual_merge?expand=1)

```python
from pathlib import Path
from typing import Any, Dict

from ruamel.yaml import YAML


def sorter(x: Dict[str, Any]):
    if wd := x.get("wd"):
        wd = int(wd[1:])
    else:
        wd = 10**10  # high
    return wd, x["title"]


yaml = YAML()
data = yaml.load(Path("endpoints.yml").read_text())
data.sort(key=sorter)
with Path("endpoints.yml").open("w") as fp:
    yaml.dump(data, fp)
```

**Pull request closed without merging**
